Activate the sites frameworks.
The sites framework seems not to be optional at all, because an exception is thrown when trying to create the database migrations for the app ("python manage.py makemigrations app").

RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.